//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview_Memo
    {
        public int Interview_Memo_ID { get; set; }
        public int Investigation_Interview_ID { get; set; }
        public string Investigation_Interview_Memo { get; set; }
    
        public virtual Investigation_Interview Investigation_Interview { get; set; }
    }
}
