//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview_View
    {
        public string Answer_Details { get; set; }
        public string Investigation_Interview_Memo { get; set; }
        public int Investigation_Interview_ID { get; set; }
        public System.DateTime Investigation_Interview_Date { get; set; }
        public string Investigation_Interview_Time { get; set; }
        public string Investigation_Interview_Location { get; set; }
        public string Investigation_Interview_Interviewee_ID { get; set; }
        public string Investigation_Interview_Interviewer_ID { get; set; }
        public int Case_ID { get; set; }
        public string Question_Details { get; set; }
    }
}
