//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Investigation_management_systemEntities4 : DbContext
    {
        public Investigation_management_systemEntities4()
            : base("name=Investigation_management_systemEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accused_case> Accused_Cases { get; set; }
        public DbSet<AccusedEmp> AccusedEmps { get; set; }
        public DbSet<Case_Handler> Case_Handler { get; set; }
        public DbSet<Case_Status> Case_Status { get; set; }
        public DbSet<Case_Verdict> Case_Verdict { get; set; }
        public DbSet<CaseType> CaseType { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Evidence> Evidences { get; set; }
        public DbSet<Evidence_Request> Evidence_Request { get; set; }
        public DbSet<Interview_Invite> Interview_Invite { get; set; }
        public DbSet<Investigation_Interview> Investigation_Interview { get; set; }
        public DbSet<InvestigationCase1> InvestigationCase1 { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<QuestionsAnswer> QuestionsAnswers { get; set; }
        public DbSet<Requester> Requesters { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Termination_Request> Termination_Requests { get; set; }
        public DbSet<case_view> case_view { get; set; }
        public DbSet<details_view> details_view { get; set; }
        public DbSet<View_3> View_3 { get; set; }
        public DbSet<View_4> View_4 { get; set; }
    }
}
